# Generated by Django 5.0.9 on 2024-09-10 01:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
    ]
