# Generated by Django 5.0.9 on 2024-09-25 00:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('gallery', 1), ('heading', 2), ('paragraph', 3), ('image', 0), ('video', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {})}, default='algo'),
            preserve_default=False,
        ),
    ]
