# Generated by Django 5.0.9 on 2024-09-26 17:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('gallery', 1), ('heading', 2), ('paragraph', 3), ('image', 0), ('video', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'icon': 'image'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'title'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('gallery', 1), ('heading', 2), ('paragraph', 3), ('image', 0), ('video', 4)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.ListBlock', (0,), {'icon': 'image'}), 2: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'title'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {})}, default=''),
            preserve_default=False,
        ),
    ]
